version: '3.5'

networks:
  public:
    name: public
    external: true

services:
  traefik:
    container_name: traefik
    image: 'traefik:1.7.2-alpine'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '80:80'
      - '443:443'
    networks:
      - public
    labels:
      - 'traefik.frontend.rule=Host:${HOSTNAME};PathPrefixStrip:/traefik'
      - 'traefik.port=8080'
    command:
      - "--defaultentrypoints=http,https"
      - "--api"
      - "--api.entrypoint=dashboard"
      - "--entrypoints=Name:dashboard Address::8080 Auth.Basic.Users:${AUTH_USERNAME}:${AUTH_PASSWORD}"
      - "--entrypoints=Name:http Address::80"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--acme"
      - "--acme.storage=acme.json"
      - "--acme.entryPoint=https"
      - "--acme.dnsChallenge.provider=cloudflare"
      - "--acme.dnsChallenge.delayBeforeCheck=0"
      - "--acme.onHostRule=true"
      - "--acme.email=${SSL_EMAIL}"
      - "--docker"
      - "--docker.watch"
      - "--docker.network=public"
    environment:
      - CLOUDFLARE_EMAIL=${CF_EMAIL}
      - CLOUDFLARE_API_KEY=${CF_API_KEY}
    restart: always
