version: '3'

networks:
  public:
    external: false


services:
  traefik:
    container_name: traefik
    image: 'traefik:1.7.2-alpine'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '$PWD/acme.json:/acme.json'
    ports:
      - '80:80'
      - '443:443'
    networks:
      - public
    labels:
      - 'traefik.frontend.rule=Host:${HOSTNAME};PathPrefixStrip:/traefik'
      - 'traefik.port=8080'
    command:
      - "--defaultentrypoints=http,https"
      - "--api"
      - "--api.entrypoint=dashboard"
      - "--entrypoints=Name:dashboard Address::8080 Auth.Basic.Users:${AUTH_USERNAME}:${AUTH_PASSWORD}"
      - "--entrypoints=Name:http Address::80"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--acme"
      - "--acme.storage=acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.email=${SSL_EMAIL}"
      - "--docker"
      - "--docker.watch"
      - "--docker.network=public"
